### ISSUE TITLE
Too much annoying dialogs when the stamina bar is empty

### ISSUE THREAD

**Issue by christopho** [wrightmat/zbom#10]
When the stamina bar is empty, a very annoying dialog pops out every time you try to use the sword, use an item or to lift something.
I suggest to show the dialog only the first time and then from time to time, and to simply do nothing the rest of the time. Or to play a very discreet sound.

**Comment by wrightmat** [comment]
I agree. This will be changed to show the dialog only once when the player completely runs out of stamina. Heavy breathing sound effects will be added when running low on or out of stamina, and the "wrong" sound will play when key presses are disabled (which only happens once out of every three or four times pressed). Sound okay?

**Comment by christopho** [comment]
Looks good to me!
