### ISSUE TITLE
Guaranteed death when falling into lava from floor above

### ISSUE THREAD

**Issue by Wuzzy2** [wrightmat/zbom#101]

**Comment by Wuzzy2** [comment]
I don't know if it's intentional or not, but if you drop into lava from the floor above, your death is guaranteed and no potion or fairy will rescue you.

First you will drop from a floor above.
Then you drop right into the lava.
Link resets, but without changing position, i.e. Link stays in the lava forever.
You will run out of health.
Maybe you have a fairy who restores your health. But her effort is futile as you just respawn, you guessed it, on the lava.

Your death is certain.

Version of ZBOM: 1.4
Version of Solarus: 1.6.0

**Comment by wrightmat** [comment]
I don't think I ever had this happen to me in testing!
I assume this happened in the Tower of Winds?

**Comment by Wuzzy2** [comment]
Yes.
