### ISSUE TITLE
Island Palace only has one boss

### ISSUE THREAD

**Issue by Wuzzy2** [wrightmat/zbom#106]
The Island Palace was surprisingly easy. It only had one boss. After that, I got immediately access to the heart container.

Version of ZBOM: 1.4
Version of Solarus: 1.6.0

**Comment by wrightmat** [comment]
Huh. Supposed to be a boss rush, so something's wrong :)
Did you ever see an error.txt file by chance?

**Comment by Wuzzy2** [comment]
The only `error.txt` I found:

```
[Solarus] [18740] Warning: The function sol.video.get_mode() is deprecated since Solarus 1.6. Use sol.video.get_shader() instead.
```

But I am not sure if this is from ZBOM or another game. It seems unrelated anyway.
