### ISSUE TITLE
Flower quest is mean and broken

### ISSUE THREAD

**Issue by Wuzzy2** [wrightmat/zbom#109]
The quest to collect plants is mean and pretty broken. There's a “secret” quest (i.e. a quest that does not appear in the quest log) in which you must find all rare flowers of Hyrule. It is given to you in that village with the tree stump huts.

I had found 16 flowers and thought for a long time there were more plants to find. I searched forever for the 17th plant which did not exist, apparently.

In that village with the tree stump huts (I don't know the village name), there is an NPC that tells you how many plants you found. I assumed for a long time the NPC will tell you when your quest is complete but I was wrong. I just casually walked into another hut only to be greeted with a reward for getting all flowers … D'oh! And all I got was a crystal ball … D'oh! Something which I could just farm or buy.
But if I talk to the person again, the dialog just repeats and I get … another crystal ball. Basically this bug gives me now infinite crystal balls …

But on the other hand, in Ordon Village, Crista keeps telling me I have found “more than half” of the species on the plant search, not that I have found all of them.
But I noticed in the shop there is now the purple potion available. It just appeared, there was no special dialog introducing it.

I cannot give you steps to reproduce because I can't recall the exact order of how I played the game.

Version of ZBOM: 1.4
Version of Solarus: 1.6.0

**Comment by wrightmat** [comment]
It was not intended to be mean! Just a late-game addition that wasn't vetted thoroughly enough. Thanks for the great ideas on how to make it better!
