### ISSUE TITLE
Can get cheap rupees from talking to tutorial NPC over and over again

### ISSUE THREAD

**Issue by Wuzzy2** [wrightmat/zbom#114]
At the first day of the game, there's an NPC who explains the basics of the game and gives you 10 rupees for listening to the bitter end.

You can repeat this as often as you like, gaining 10 rupees every time, granting you quick and cheap rupees by just button mashing.

I suggest the reward should only be given once.

It's not a critical problem, as the NPC will be gone after the first day.

ZBOM version: 1.4
Solarus version: 1.6.0

**Comment by wrightmat** [comment]
This was a bug I decided was a feature. At this point you can only hold 200 rupees, and you're likely to max out by the end of the first dungeon anyway, so this is no big deal.

**Comment by Wuzzy2** [comment]
Heh. :D
