### ISSUE TITLE
Suggestion: Add more warp points in the North

### ISSUE THREAD

**Issue by Wuzzy2** [wrightmat/zbom#117]
The amount of warp points in the North seems way too low IMO, and the few warp points are pretty sparse.

I have found a grand total of 4 warp points in the North:

* Ruto Town
* Calatia Peaks
* Old Kasuto
* Three Eye Rock

Did I find all? Please add more warp points at strategic positions. There is a huge gap in the center of the map and you generally have to walk a lot in the North.

**Comment by wrightmat** [comment]
Yes, you found them all. But you're right that all of them warp between the north and south, with none that warp within the north. I'm going to add two more warp points that link Mido Town (center west) to Nabooru (north east).
