### ISSUE TITLE
Script errors

### ISSUE THREAD

**Issue by christopho** [wrightmat/zbom#12]
Here are some errors I had during my playthrough of today, with the current git version (commit f9b563a):

- [x] Error: In on_activated: [string "maps/204.lua"]:124: attempt to index global 'room11_belt_1' (a nil value)

- [x] Error: No such dialog: 'shop.bomb_bag'

And a lot of
- [ ] Error: In on_update: [string "maps/71.lua"]:93: Cannot start dialog: another dialog is already active

**Comment by wrightmat** [comment]
Error #1 is corrected. Thank for the report!

Do you know what map called Error #2?

Were there any other errors in map 71? That line shouldn't have even been called...

**Comment by christopho** [comment]
2. It was a obviously a shop, but which one? Maybe the one of the Ordon Village.
3. I don't think there was any other error. I will try to give you more details if I have this error again.

**Comment by wrightmat** [comment]
It looks like it was the Ordon shop - fixed! Thanks!

**Comment by christopho** [comment]
Here are the ones of today's stream!
(I removed duplicates)
- [ ] Error: In on_draw: [string "maps/138.lua"]:39: attempt to index global 'torch_ordona' (a nil value)
- [ ] Error: Map '84': No such destination: 'from_sewer'
- [ ] Error: In on_draw: [string "maps/45.lua"]:49: attempt to index global 'torch_fire_2' (a nil value)
- [ ] Error: In on_draw: [string "maps/68.lua"]:61: attempt to index local 'torch' (a nil value)
- [ ] Error: In dialog callback: [string "maps/2.lua"]:553: Cannot start dialog: another dialog is already active

**Comment by wrightmat** [comment]
@christopho, maybe you can help me figure these out? "attempt to index global 'torch_ordona' (a nil value)" comes from the line "torch_ordona:get_center_position()". When I used "map:get_entity("torch_ordona"):get_center_position" in the past, I got a different error (don't recall the exact wording) and my script didn't work correctly. This way, everything works but I still get a (seemingly unnecessary) error. Am I actually doing something wrong?

"Cannot start dialog: another dialog is already active" is a similar issue, where the game functions as I intend it to, but this error fires occasionally. Do you know why?

**Comment by christopho** [comment]
Regarding the "Cannot start dialog: another dialog is already active" error, are line 553 of maps/2.lua this seems straightforward: if several saved booleans are true here, several dialogs are started. Maybe you just forgot to use some "else" here?

About the torch_ordona issue, wow, the script of map 138 seems to do crazy things. I don't understand what you are trying to do. Why create a game:on_map_changed() event from a map script? Are you trying to detect when the player comes back later on the same map? But several maps seem to do that. So every time one of these maps is entered, the game.on_map_changed event is replaced by another function.

Anyway, as you know, writing torch_ordona like a global value looks up in the map. More precisely, in the map of the current script file, not in map currently running. This is why it gives nil: at this point, the map of the current script file is finished, since we are after game:on_map_changed(). Even if the hero happens to be now on a new instance of the same map, in the script of the old, finished map, entities are all nil. However, writing map:get_entity("torch_ordonna") as you mentioned should not be nil, because here the map variable is the new one, since it is the parameter of game:on_map_changed()! Tricky, tricky!
But I still don't understand what you are trying to do :)

**Comment by wrightmat** [comment]
That's to display an overlay when Ordona speaks, and is probably old code that I adapted from something else, got to work, and never looked at again, haha.

If I re-write it and place a map:on_draw() function inside map:on_update(), everything works correctly, but I get an error when changing maps: "[strings: "maps/11.lua"]:141: attempt to index torch_1 (a nil value)". I guess I still don't understand how I can get an error from map 11 when my hero is in map 10?

**Comment by christopho** [comment]
I am not sure about that error from map 11 when the hero is on map 10, but why create a map:on_draw() function from map:on_update()? map:on_update() is called at every cycle, like 60 times per second.

To display an overlay, you can do it directly from map:on_draw() (outside of any other map event).

    local map = ...
    local game = map:get_game()

    local overlay = nil

    function map:on_draw(dst_surface)
        if game:get_time_of_day() ~= "night" and torch_overlay ~= nil then
            local screen_width, screen_height = dst_surface:get_size()
            local cx, cy = map:get_camera_position()
            local tx, ty = torch_1:get_center_position()
            local x = 320 - tx + cx
            local y = 240 - ty + cy
            torch_overlay:draw_region(x, y, screen_width, screen_height, dst_surface)
        end
    end

    function some_switch:on_activated()  -- For example
        overlay = sol.surface.create("entities/dark.png")
        torch_overlay:fade_in(50)
    end
end

**Comment by wrightmat** [comment]
It's been a while, but I think the reason why I did the convoluted way initially because with the way you have it outlined above, I'm still getting the error: "[strings: "maps/11.lua"]:128: attempt to index torch_1 (a nil value)" when the player changes maps.

When I first started making this script (which I then duplicated to like 10 different places where the same thing happens), this threw and error and the game:on_map changed() method did not - now both are throwing errors, so I'm guessing something changed.

**Comment by wrightmat** [comment]
Nevermind,,, setting torch_overlay to nil after the fade fixed that map transition error.

Doesn't that mean that map:on_draw from the OLD map is called at least once on the new map? Is that to be expected?

**Comment by christopho** [comment]
You are right, this probably probably means a bug of the engine. map:on_draw() should no longer be called once the map is finished.
