### ISSUE TITLE
Bugs in swamp temple

### ISSUE THREAD

**Issue by Wuzzy2** [wrightmat/zbom#120]
I have a suspicion there is something wrong with the swamp temple (purple water) in the North.

So I managed to reach 6 rooms unlock all doors, collect everything, open all chests. Except that one chest in the purple water in the bottom left room.

In the top left room, I figured out how to push both buttons. When I move the block to the upper button, the door to the room below unlocks (IIRC). When I push this button again, nothing changes.

When I move it to the lower botton, the door in the water opens, and I hear the “treasure” sound, but nothing else happens (it seems). When I push both buttons simultanously (with the help of Hebra's Cane), nothing changes. I tried pushing both buttons in a different order, without Hebra's Cane, but the end result is always the same. I just can't get rid of the water in the lower left room.

In the lower left room, there is this underwater chest with the door. I can't get rid of the water, but the door is open (opened by the button)? Is this intentional? Shouldn't the water disappear?

Also, for some weird reason, at some point in time, this chest became opened but I am very sure I have never opened this chest myself.

There is another bug: When I start from the entrance and just use my pegasus boots to run all the way up to the first stairs, Link will run into the next room, but BELOW the floor.

**Comment by wrightmat** [comment]
Actually the top button opens the door and the lower button drains the water. The water returns after 20 seconds though, so it's possible you missed it. The door in the room with the drainable water is always open.
I'm going to add camera pans to make the changes more apparent. I'm also extending the drained time to 60 seconds. I also fixed the running thing. Thanks!

**Comment by Wuzzy2** [comment]
Nothing happens when I push the lower button, however. I ran to the lower room as fast as possible, the water is still there (1.4).

**Comment by wrightmat** [comment]
It requires a block to be activated - did you push the block onto it? I tested it yesterday and it worked for me.

**Comment by Wuzzy2** [comment]
What do you mean with “activate a block”? Yes, I pushed the button by pushing the block from the dungeon onto it.

Maybe check my conf file I posted earlier, for weird variables and such.

Note I did NOT test the latest bleeding edge, only 1.4.

**Comment by wrightmat** [comment]
Sorry, meant to say "activate a switch" :)

**Comment by wrightmat** [comment]
Requires a block to be activated - as in you can't just step on it. Wanted to make sure you pushed a block onto it and still didn't get a reaction, but it sounds like you did.
I didn't change anything related to the block activation before my test (so it shouldn't matter whether running 1.4 or dev) so I'm not sure how to recreate this.
