### ISSUE TITLE
Replace DOCX manual with ODT or PDF

### ISSUE THREAD

**Issue by Wuzzy2** [wrightmat/zbom#121]
I'm unable to read DOCX files, so I can't read `manual.docx`.

Please replace this file by a non-proprietary format like ODT or PDF. In my opinion a game that prides itself to be “free, open-source” should also use free, open-source file formats. Thanks for your attention.

Bye.

**Comment by wrightmat** [comment]
A PDF version is included in each version's compiled archive. The docx is necessary for me to be able to edit, and will remain.
