### ISSUE TITLE
Swamp temple issues

### ISSUE THREAD

**Issue by goodgame111** [wrightmat/zbom#127]
1. Two things here - a) You can get stuck while jumping off the platform (see swamp1.jpg); b) if you don't have the rito feather, then the stairs do not lead you up to the platform, instead you appear to go between the stairs and the platform and instead go "under the map".

![swamp1](https://user-images.githubusercontent.com/65648690/82417452-90273480-9a49-11ea-96e1-95c937fe0b90.jpg)

2. The underwater chest doesn't appear to be obtainable (see swamp2.jpg)

![swamp2](https://user-images.githubusercontent.com/65648690/82417460-92898e80-9a49-11ea-83ba-3f628c95e053.jpg)

**Comment by wrightmat** [comment]
There's a switch in the room above that drains that swamp water. You're right though, the stairs are broken.
