### ISSUE TITLE
Snowpeak cave dungeon issue

### ISSUE THREAD

**Issue by goodgame111** [wrightmat/zbom#130]
I don't have a screenshot for this, but the issue is as follows: on B1 of this dungeon, right before the boss door, there is a large room with star-shaped tiles that shift holes around on the floor when stepped on.  The top right hand tile cannot be reached unless you obtain the feather, since it is surrounded by holes.  This tile also makes holes disappear before the boss door, so it must be pressed prior to fighting the boss.
The problem is that, at this point of the game, it might not be likely for the feather to be obtained, unless referring to the FAQ, so I was stuck here until after obtaining the feather.  It might be a good idea just to put blocks or pots across the pit from the tile, so you can hookshot over the hole and press the tile in the process, otherwise the trading quest will need to be completed before finishing this dungeon.

**Comment by wrightmat** [comment]
Actually there is another star switch two rooms south :) The solution to this section of the dungeon is to step on that switch south of that room, then hookshot across the pit that appears in that room by attaching to the ice blocks. Then you can easily get to the boss door.
