### ISSUE TITLE
Exectutable: Solarus not found

### ISSUE THREAD

**Issue by ShalokShalom** [wrightmat/zbom#134]
When I run zbom, it tells me: 

Line 2: Solarus: Command not found

Wouldn't it be solarus-launcher or solarus-run?

garuda Linux

**Comment by qwertz19281** [comment]
You can also use the Solarus Launcher and add the .solarus archive file or the quest folder (the folder that contains the "data" folder, not the "data" folder itself), or use `solarus_run` with the path to the .solarus or quest folder as argument.

**Comment by ShalokShalom** [comment]
thanks
