### ISSUE TITLE
Stamina bar is cut?

### ISSUE THREAD

**Issue by Diarandor** [wrightmat/zbom#22]
I think that your stamina bar is cut (it is not completely shown), but I am not sure at all.

**Comment by wrightmat** [comment]
It's not cut, the right side of the bar just isn't drawing for some reason. This wasn't a priority, but maybe I'll get a chance to look at it soon. This bug has no effect on your stamina or gameplay in general.

**Comment by wrightmat** [comment]
Nevermind - looking back at the script, I just forgot to draw the right side! Fixed!

Thanks @Diarandor for all the awesome bug reports!
