### ISSUE TITLE
Sound of chest played too many times

### ISSUE THREAD

**Issue by Diarandor** [wrightmat/zbom#23]
In the second level (the pyramid), there are some rooms where you play a sound (if you have the compass) because there is a hidden chest. For instance, in the room with 3 switches and 2 statues. The problem is that, before solving the puzzle, each time the hero walks above the sensor at the entrance of the room, the sound is played. It should only play once (each time you enter the room and before solving the puzzle) and then disable the sensor (maybe using the separators between near rooms).

PS: I think that sometimes there are problems with maps of levels, which are not correctly updated (showing the new rooms you visited).

**Comment by wrightmat** [comment]
Don't think I can use the separators because of the way I coded this. What do you think about disabling the sensor for a period of time and then re-enabling? Is 5 seconds long enough, or should I do longer?

**Comment by wrightmat** [comment]
And I have had the detection issue occasionally as well. I had increased the size of the sensors once to help with this, but I'll do it again.

**Comment by Diarandor** [comment]
What I mean is that the sound should better play once, and no more times, each time you enter the room (before solving the puzzle). But this is just my opinion, this is not important.

**Comment by wrightmat** [comment]
I know that's what you mean, but I'm not sure I cam accomplish that. Instead, I can at least prevent the sound from chiming repeatedly if you walk over the sensor.
