### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#25]
Hi,
I've been playing Book of Mudora, its great ! A few bugs to report since I am now stuck at the tower of winds. I know its still work in progress so I might be pointing out unfinished work so sorry in advance about that : 
- On the six floor of the tower of winds, after pushing the switches, blocks appear behind the laser shooting statues. I assume they are for using the hookshot to pull yourself through the holes. But it doesn't appear to work, the hookshot just bounces off the blocks
- I've done the exange secondary quest and got the tasty meat. I am not able to exange it to the guy at the entrance of the cave of ordeals so I cannot complete the quest and I don't have the access to the cave
- I've bought the shovel (subrosian shop) and the hammer (goron market). But if I try to use these objects, I am no longer able do move (the game doesn't freezes though, I am able to access the inventory)
- I've collected enough subrosian ore to exange with the barman at kakorico village but I am not able to speek with him, preventing me from finishing the quest.
- In the tokay village, you can get treasures for free ! If you press action in front of the treasure, you pay but if you speek with the tokay next to it, you get it for free.
- it seems that the  position indicated on the map is staggered from the actual real position

Jeff

**Comment by proutout** [comment]
- hidden village, you can go through the fortune teller's house (from the top side)

**Comment by proutout** [comment]
- I've got the bottle from the thief in kakarico cemetary but the thief is still there

**Comment by proutout** [comment]
- you can go through the waterfall on east lake hylia from one side or the other

**Comment by proutout** [comment]
- the arrow shooting game in hyrule town doesn't seem to be working like it should be

**Comment by proutout** [comment]
- in the snowpeak caverns at level B2, the room with the alchemy stones, I can't solve the puzzle. The sign says to create your own ice block but the ones I create with the icerod don't seem to do anything on the swithches

**Comment by proutout** [comment]
- you can buy a wooden shield after getting the light shield (which you cannot get back after)

**Comment by proutout** [comment]
- the "roulette" game in Hyrule town is free (no rupees taken) and you don't get any rewards (no rupees added)

**Comment by proutout** [comment]
- north of anouki town, you can enter the igloo (which is on the ice) by the top

**Comment by wrightmat** [comment]
Hi Jeff! Thanks for the reports. In the future, it's easier to correct these bugs if they're logged as separate issues instead of one long string of bugs. Also, was an error.txt file generated in the game's directory that you could send to me? That would be a huge help in sorting out some of the more vague bugs.

**Comment by wrightmat** [comment]
The Tower of Winds bug should be corrected.

Why can't you trade the meat? Is the Moblin not there, or will he not speak to you? If he's there, is there a quest bubble over his head?

The shovel and hammer have worked in my play test (good job already getting those by the way!), so if you have an error.txt file to share, that would be a huge help.

It should be Alchemy Stone that you're collecting for the bartender in Kakariko. Does he not speak at all, or does he not reference the collectibles?

Tokay bug is fixed.

The map is still a little bit of a work in progress. It's come a long way though!

**Comment by proutout** [comment]
[error.txt](https://github.com/wrightmat/zbom/files/59165/error.txt)

Above the error file. For the meat trading, the moblin is there, there is a quest bubble over his head but I can't talk to him. For the bartender, he doesn't speek to me at all.

**Comment by wrightmat** [comment]
If you can also send me your save game file, I should be able to fix the last few bugs. It can be found in the home directory (C:/Users/[username] in Windows) under .solarus/zbom/save[number].dat

**Comment by wrightmat** [comment]
Kakariko bartender bug is fixed also.

**Comment by proutout** [comment]
I can't seem to be able to send .dat files on github. Should I e mail it to you?

**Comment by proutout** [comment]
Finished with the bugs, hope I 'm haven't bothered you too much.

Jeff

**Comment by proutout** [comment]
Here you go : my save file 


    On Friday, December 11, 2015 2:30 PM, Matt <notifications@github.com> wrote:
 

 Kakariko bartender bug is fixed also.—

**Comment by wrightmat** [comment]
Sure, email directly to wright.matt.a@gmail.com. It doesn't seem to let you send via GitHub.

No bother at all! these report are very helpful to fix these things for future players as well.

**Comment by wrightmat** [comment]
Got it.

I was able to get the tasty meat traded to the moblin no problem. There are some differences between my dev version and the official 0.6 release, so this should work in the 0.7 release.

I had neglected to implement an important script for the shovel, so that now works.
