### ISSUE TITLE
Fairy north territory

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#27]
The fairy in the north territory doesn't reference the collectibles even I've got 99 of them (can't remember which treasure it is but i've got 99 of all)

**Comment by wrightmat** [comment]
Wow - you're further than I thought! Good work!
I've fixed the source of this bug, but my brother and I are working on a new mini-dungeon for the next release, and that Great Fairy will be moving. She gives you the most powerful sword in the game, and I haven't fully tested it yet anyway, so it's probably best you don't get it yet :)
