### ISSUE TITLE
Airship repairs

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#28]
Bug noticed after restarting the game :  After completing the first two dungeons, I went back to the first one (forest) and reopened the final chest to get the page of mudora's book. Again, at the exit, the monkey took it. Then I went back to the beach, and the Gerudo garding the passeway to the desert asked me again to go and fetch the ship pieces in the second dungeon even though I had already completed the second dungeon before and given her the pieces.

I didn't continue the game after that so don't know the impact it has afterwards.
 
I know this one is a bit farfetched

**Comment by wrightmat** [comment]
Still important to fix! Thanks for the report!
