### ISSUE TITLE
scarecrow goat ranch, ordin village

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#30]
If you're in front of the scarecrow in the goat ranch ordin village, the blue action circle appears with "speak"on it, but pressing the action button doesn't do anything. Same thing with the goats

**Comment by wrightmat** [comment]
Not a bug. Goats and Scarecrows don't speak :-)

It's actually a limitation of the engine where all NPCs show the "Speak" action, regardless of what happens when you interact with them.
