### ISSUE TITLE
Crista's dialog is broken

### ISSUE THREAD

**Issue by wrightmat** [wrightmat/zbom#37]
When speaking to Crista, she will only reference the Lumberjack ("crista.4.shop"), when the dialog should vary based on savegame variables. This affects all the savefiles I've tested, each of which should've shown a different dialog.

When testing the custom entity script, game:get_value() calls would not print from within entity:on_interaction(), which could be part of the problem.

This worked with Solarus 1.4.4, so it this an engine bug for 1.4.5?

**Comment by christopho** [comment]
Feel free to open an issue in the solarus project if you suspect a bug in the engine.

**Comment by wrightmat** [comment]
Further testing revealed that I was an idiot :)
