### ISSUE TITLE
impossible to complete the torch quest at the beginning of the game

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#38]
A torch blocks the access to the other torches

![image](https://cloud.githubusercontent.com/assets/16241277/12448103/21922b88-bf74-11e5-967a-9304748004b4.png)

**Comment by wrightmat** [comment]
Thanks for the picture - that's a big help!

**Comment by wrightmat** [comment]
Since it was just released, I silently updated the existing 0.7 version to include this fix. Feel free to re-download if you'd like. Thanks again for the report!
