### ISSUE TITLE
No effet of torches in hyrule town sewers

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#39]
First of all great job in fixing all the bugs!!!!!! Playing through a second time so reporting new bugs!

The torches don't make any light in hyrule town sewers (right torch on the picture)

![image](https://cloud.githubusercontent.com/assets/16241277/12612264/b1935fe0-c4f1-11e5-94c0-cf391297fdde.png)

**Comment by wrightmat** [comment]
Thanks!

Yes, with the current version of the engine I don't have a way to do an overlay for the hero (as seen in the pic) and also an overlay when torches are lit. If they were to overlap it would look really bad.

When the engine supports shaders in the future, this will be possible, but with sprite overlays it is not.
