### ISSUE TITLE
Inconsistensies if going to pyramid before completing first dungeon

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#42]
You can access the pyramid before completing the first dungeon.

If you go to the pyramid before going to the first dungon, there are minor inconsistensies : 
- when you get the magnetite, a message talks about the gerudos you haven't met yet
- when you leave the pyramid (which you can't complete without the bow), the light spirit says we haven't got all the gerudo parts which we know nothing about

**Comment by wrightmat** [comment]
I really appreciate the sequence break finds, thanks! These are tough for me to find, and I want sequence breaking to be possible and to make sense.
