### ISSUE TITLE
Vines which can be picked up in first dungeon intermediate boss room

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#44]
Not a bug, just wandering why the vines at the bottom of the pre boss room are the only ones that can be picked up in the dungeon? (doesn'twork for the top ones of that same room or in other rooms)

![image](https://cloud.githubusercontent.com/assets/16241277/12614751/1ff9d1d4-c502-11e5-8a9d-42fc0b69eb52.png)

**Comment by wrightmat** [comment]
Technically that is a bug, because the intent was not to be able to carry them! I wanted the hero to be able to cut all of the vines for an extra chance at hearts during the battle, but had forgotten to implement all of the directions.
