### ISSUE TITLE
carried vines disapear when walking

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#45]
If you walk with a carried vine in the first dungeon, it disapears when you walk are reapears when you stop
![image](https://cloud.githubusercontent.com/assets/16241277/12614934/ff8e6918-c502-11e5-925f-0b6abf7ef9a9.png)

![image](https://cloud.githubusercontent.com/assets/16241277/12614927/f45f3e00-c502-11e5-9620-412db1e4766b.png)

**Comment by wrightmat** [comment]
Related to #44 - vines should not be carried.
