### ISSUE TITLE
Infinite access to deku sticks and mystic jade

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#46]
Not sure if its a bug but just east of the beach access, there are two patches of grass and each time you cut them you get one deku stick and one mystic jade. If you go just up to next screen and go back down, the patches of grass are back with the deku stick and mystic jade giving you an infinite supply!
Throughout my first playthrough, i've noticed a couple of these so if you want me to report them or if its intended, let me know ! 

n![image](https://cloud.githubusercontent.com/assets/16241277/12615249/d3b1392c-c504-11e5-9e7e-7df155fe9e23.png)

**Comment by wrightmat** [comment]
Sort of an easter egg - reward for thorough exploring :)

**Comment by proutout** [comment]
Nice :)
