### ISSUE TITLE
Green or blue potion ordon village

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#50]
Two sort of bugs , applies for green and blue potion. Not a big deal but would be nice if the player is warned (message that the potion is available changed) :   :

- After you bring 10 deku sticks, and then get the message that the potion is available, at first there is nothing there (screenshot : no green potion). You have to exit the shop and reenter it for the potion to be available.

![image](https://cloud.githubusercontent.com/assets/16241277/12616119/c63a149e-c509-11e5-91ae-8312ecc1b87c.png)

- The message says you have the first one free. Not exactly true : if you don't buy the potion that cost 0 rupee, that you leave and reenter the shop, it costs 100 rupee even if its your first one. 
Didn't have room in my bottles so just thought, i ll get it later ......but too late.

**Comment by wrightmat** [comment]
I noticed this as well. I had just changed up the deku stick potions functionality and hadn't had a chance to work out all of the bugs :) I'll take a look at this one soon.
