### ISSUE TITLE
Inconsistensy at the beginning if you don't have the lantern

### ISSUE THREAD

**Issue by proutout** [wrightmat/zbom#57]
If you don't get the lantern and you go to the end point of the race, this message is false, the race is not on !
![image](https://cloud.githubusercontent.com/assets/16241277/12717633/60eb6f14-c8e9-11e5-83e7-ba30669c9148.png)

**Comment by wrightmat** [comment]
Another nice find! How many times have you played? :-)

**Comment by Diarandor** [comment]
He deserves to appear in the credits of the game as the main tester XD. :D

**Comment by wrightmat** [comment]
I agree! I think I am going to add a few testers to the credits :-)
