### ISSUE TITLE
Various "item not saved/has no amount" errors

### ISSUE THREAD

**Issue by wrightmat** [wrightmat/zbom#6]
Error: In on_started: [string "items/arrow.lua"]:13: Item 'bow' is not saved
Error: In on_started: [string "items/quiver.lua"]:16: Item 'bow' has no amount
Error: In on_started: [string "hud/rupees.lua"]:26: Item 'rupee_bag' is not saved

All the above errors have popped up at random times. Doesn't always happen and can't seem to reproduce reliably. Chrisopho doesn't know why these errors would appear (especially inconsistently) since the scripts are written correctly.

**Comment by wrightmat** [comment]
"Fatal: the item 'bomb_bag' is not saved" is probably a related issue - happens seemingly randomly (one out of about every 6 games started?) when starting new save file.

**Comment by wrightmat** [comment]
I think it has something to do with all items not being fully created before attempting to be initialized in savegames.lua/savegame_menu:set_initial_values(savegame). Not sure how to fix it though - build in a delay somewhere in such a way that it doesn't mess other things up?

**Comment by Diarandor** [comment]
Hi! I tested your game until I got the sword, and found a bug which is probably the same issue. After starting the game, when I picked rupees or magic bottles, the counters did not update; the rupee counter was still 0 after picking lots of rupees, and the magic bar did not fill when picking magic bottles or at least the image did not change (it only decreased when using fire). However, after saving the game, exiting to the menu and opening the game, everything worked fine and the counter showed the rupees I had picked before saving the game.

So this probably means that some variables are not correctly initialized when creating a new game (maybe you already know that). I hope this helps.

**Comment by MetalES** [comment]
I also got some errors, I put them here for debugin :

-In the shop near hyrule castle (let's name it so), you can't buy hearts, there is no dialog to display.
-In the same map, there is an error line 69 (2.lua) : Attempt to compare number with nil
-Shop : The icon for the shield in dialog is wrong
-Castle : You can traverse the curtain in the room where there is the 2 thrones

These are the only errors that I got during gameplay, I did had some wrong warps first but it seem that it was some kind of savegame issue thing with the older beta

@diarantor : Oh, I get these too, he's using Mercuris' Chest new hud code which need manual refresh (it seems ?)

**Comment by wrightmat** [comment]
@MetalES : The first three have been fixed for the next release. The last one is intentional :)

@Diarandor The HUD freezes for some reason after the Ordona dialog when you win the maze race. I'm not sure why. With my old HUD, I knew how to reinitialize it, which fixed the problem. But with MC's new HUD, I don't. Do either of you know how to reinitialize it?

**Comment by Diarandor** [comment]
Yes.

I would try to restore the initial values of the attack and action commands, so you will need to save them in some variable (with the get_custom_command_effect) when you open the menu and restore them back when you close the menu. (Also, you might need the (non built-in) function game:clear_interaction() to restore the behaviour, in case there is some portable entity involved in the problem, but probably you will not this.)

If this does not work, give me the link to your script and info of what happens and I will tell you what yo do. Sorry for the problems (using my scripts was really risky for your hud).

**Comment by wrightmat** [comment]
@Diarandor Haha, no problem! Generally, the new HUD is better, there are just a few kinks to work out! I appreciate your help!

The script is at https://github.com/wrightmat/zbom/blob/master/data/maps/12.lua and I have a comment at line 57 indicating that the HUD freezes at some point during this "cut scene". You can play the game after this, but the HUD doesn't update. Restarting the game restores correct behavior.

**Comment by Diarandor** [comment]
Another problem you may have is that you have a portable entity near the border of the map and you are close to it, so the hud changes. If then you change map, the hud will still be changed (and the hero will try to lift an entity which is not there and may be an error). This can be solved if you write the line
```game:clear_interaction()```
in some of the following events:
hud:on_map_changed() -> This is probably the best option.
game:on_map_changed()
game:on_map_finished()

**Comment by Diarandor** [comment]
When you know the answer, tell me if that solved the problem of the HUD.

**Comment by Diarandor** [comment]
I noticed now that you are using a dialog in that part of your script.
In the event function dialog_box:on_finished(), you can find it here
https://github.com/wrightmat/zbom/blob/master/data/scripts/menus/dialog_box.lua)
the hud resets to nil (you can read the code inside that event function), and that might be related to your problem, but I don't know.

**Comment by wrightmat** [comment]
The HUD resetting to nil in the dialog box is intentional to clear out the custom action like "Back" that's present during the dialog. I added game:clear_interaction to the hud:on_map_changed() and dialog_box:on_finished() events, and haven't noticed any detrimental effects. I still need to re-test that intro to see if it actually fixes anything. I don't believe I'm using portable entities anywhere currently though.

**Comment by Diarandor** [comment]
Bad news: I was completely wrong, you don't need to add the line "game:clear_interaction()", so change it back if tou added it, sorry. 

The good news: the problem is that in the function "end_race_won()" you are calling "sol.timer.stop_all(game)", which stops all the menus associated to the game. But in your hud script, in the function "check_hud()" we have a loop using a timer "sol.timer.start(game, 50, check_hud)". The problem is that we are stopping that timer in your map script. Probably the hud you had before worked differently if it did not use a timer for that, or maybe the hud timer was attached to a different entity or list, I don't know.

**Comment by wrightmat** [comment]
@Diarandor you're a genius! That took care of the HUD problem!

The funny thing is that I'm 99% sure that none of this was related to the original "item not saved" errors :)

**Comment by Diarandor** [comment]
I am not a programmer, so I am not sure about this: you are using several scripts which are being started from one script, so I assume they are being executed in parallel (is that true?). If that is correct, maybe sometimes the script where you initialize some of the variables is being called after the other script where you are using them (that would also explain why these errors do not happen always). If that is the problem, it would suffice to call the secondary scripts at the end of the script where you initialize the variables. Do you think this makes sense?

**Comment by wrightmat** [comment]
Yeah, that my thought too. I initially wasn't sure how to build in a delay without other problems though. Now I've built a delay between set_initial_values(savegame) and savegame:start() and can no longer recreate the error. Closed!
