### ISSUE TITLE
Metal Ball cannot be lifted after being thrown

### ISSUE THREAD

**Issue by MetalES** [wrightmat/zbom#60]
I just leave this here, it might be related to Diarandor's portable entities script, but it makes mini-dungeons that uses this unbeatable

**Comment by Diarandor** [comment]
I have this problem too in my quest since some time ago, but I have not tried to repair it yet. Probably some of the changes in the last version of solarus have broken something of my scripts. I have to find what it is and fix my scripts again.

**Comment by wrightmat** [comment]
Yes, related to #52. Thanks for the report!

**Comment by Diarandor** [comment]
Note that if you set the number of bounces to 0, the entity is put on the ground directly. You can test the script with different values to customize:
-number of bounces,
-heights reached on each bounce (the first one is better to be kept with "same" value, which is the initial height when carried by the hero),
-distances for each bounce,
-durations for each bounce,
-and many other properties like damage, etc.

**Comment by Diarandor** [comment]
It would be cool to code the magnet and allow to use it with cannon balls, like in the oracle games. This is now possible for you, and I will code it some day in my game.

Maybe Solarus 1.6 will have carried entities like these (I will help christopho with my ideas). That would allow to remove the script of generic_portable entities, or at least most of its code. But the scripts for saving info between maps would still be necessary, obviously.

PS: I don't know if you tested it but, if you throw a portable entity that saves position between maps (these have a unique indentifier and you have to set the boolean variable entity.is_independent to true to make it work), and leave the map when it is falling, when you come back to the map it appears in the middle of the fall in the same precise instant, the same height and the same bounce where it was!!! (I have not tested this in your game, you should check it, but it does work in my game.) :D

**Comment by wrightmat** [comment]
I planned to play around with the new customizations :)

I probably won't add content like cannon balls, as I'm trying to get the game released, but who knows if I won't add further content later!
