### ISSUE TITLE
Game "freeze" after Tower of the Winds completion

### ISSUE THREAD

**Issue by carlcorder** [wrightmat/zbom#67]
This issue is present in zbom 1.0 & 1.0.1

After defeating the Helamroc King and exiting the Tower of Winds, a dialogue appears to congratulate the hero for restoring the Book of Mudora. After the dialogue is complete I am unable to move, use items or the action button. I can however still press "start" and enter into the menu to view the quest status, navigate around etc..

It looks like just the hero is frozen as the clock in the bottom right still moves and time passes (eventually the sun rises) and the lantern magic still expires.

Two curiosities that I noticed (which are most likely unrelated)

1) The dialogue said the Book of Mudora is complete, but the quest status shows only seven pages (looks like one is missing?)

2) I have a red tunic, I don't recall ever acquiring this.

![tow-freeze](https://cloud.githubusercontent.com/assets/6445816/18758453/cb4c8fb4-80bd-11e6-871e-45cb64561442.png)

![quest-status](https://cloud.githubusercontent.com/assets/6445816/18758465/d3e1bbf4-80bd-11e6-8f1f-3c94cd66e1b3.png)

![quest-status-red-tunic](https://cloud.githubusercontent.com/assets/6445816/18758469/d85b348a-80bd-11e6-98e7-0037525d2296.png)

**Comment by wrightmat** [comment]
The main issues sounds like a bug - was there an error.txt file generated that you can send to me?

1) The book is complete, but there's one temple left, which is what the pages on the quest status screen represent. The book on the item inventory screen should be complete!

2) How did you get the blue tunic? The tunics are one item, so if you get the blue it has to give you the red automatically. I thought I had designed things so you couldn't get the blue tunic before the red...

**Comment by carlcorder** [comment]
This is what I have in the error.txt:

[Solarus] [16900] Error: In dialog callback: [string "maps/55.lua"]:33: attempt to index global 'torch_overlay' (a nil value)

I can actually move around outside of the tower for about 1 second  before that dialogue occurs. Immediately after the text is finished, I am "frozen" in place.

**Comment by carlcorder** [comment]
It looks like the torch overlay error is basically keeping the hero:unfreeze() (line 35) from getting called?

**Comment by wrightmat** [comment]
No, it's related to an error in the overlay script. I'm actually re-writing all of them for the new tone_manager (day/night) script. I'll just release a new version when I'm done with all of that, but it may be a while. You should be able to get past this dialog if you save and quit since it's not really required.

As for the save file, I'm not entirely sure. In Windows it's in the User folder under a .zbom subfolder. The save files are names save1.dat, save2.dat and save3.dat.

**Comment by carlcorder** [comment]
Unfortunately, even if I save & quit, after resuming the file I start right outside the entrance to the tower and I am greeted with the same dialogue.

Also, thanks for the lead. I found the save file here:

/home/carlc/.wine/drive_c/users/carlc/.solarus/zbom/save1.dat

Since you said this is in relation to the overlay script, and there is not much I can do about that, I might try tampering with the save file. Perhaps there is a flag I can set to get me past this point. Any suggestions?
