### ISSUE TITLE
Fatal: Value 'i1806' is not a boolean

### ISSUE THREAD

**Issue by soerensen3** [wrightmat/zbom#70]
I get an error when I enter the building on the screenshot making solarus crash. I got a similar error on other locations too, but I don't remember where.
**OS**: Fedora 24 4.8.4-200.fc24.x86_64 **Solarus**: 1.5.0 **ZBOM**: 1.0.1

Refer to the map to find location. Savegame and settings are attached.
![screenshot from 2016-11-26 20-44-16](https://cloud.githubusercontent.com/assets/8309189/20642796/3fa0ad6c-b419-11e6-9df8-426b55d9f161.png)
![screenshot from 2016-11-26 17-40-06](https://cloud.githubusercontent.com/assets/8309189/20642786/e5a56776-b418-11e6-9300-688d68ba6d15.png)
[zbom-save.zip](https://github.com/wrightmat/zbom/files/614414/zbom-save.zip)

**Comment by christopho** [comment]
As of Solarus 1.5.1, the engine will no longer crash in these situations but will show an error message instead.

**Comment by wrightmat** [comment]
Thanks for the report, and thanks @christopho!
