### ISSUE TITLE
Missing room in Abandonned Pyramid minimap

### ISSUE THREAD

**Issue by MetalES** [wrightmat/zbom#75]
![sans titre 2](https://cloud.githubusercontent.com/assets/4288633/21534043/9965498c-cd61-11e6-8653-dbf7f924f718.png)

There are doors, this room isn't secret, and can only be seen if the dungeon map has been obtained and even with the dungeon map (obtained after passing this room), it remains invisible

**Comment by wrightmat** [comment]
It kind of is a secret, because it's only a shortcut. I don't think I want it on the map if you haven't explored that area, but it does need to appear when you've been there.
