### ISSUE TITLE
(Ore)You get in second dungeon

### ISSUE THREAD

**Issue by Ezkazelda** [wrightmat/zbom#77]
In the second dungeon, while retrieving the propeller and dins pearl for the pirates. You also get some ore(forgot its name). When you get the ore, it goes into you inventory in slot(right to left and down to up, bottom left is 1-1) 6-2. Then when you get the propellor, the ore disappears and the propeller goes in that slot. What you get dins pearl, the same thing happens to the propeller. Hope this helped!

**Comment by wrightmat** [comment]
Yes, that's intentional. All three are essentially one "item" that is used only for this quest.
