### ISSUE TITLE
Bridge and map

### ISSUE THREAD

**Issue by Ezkazelda** [wrightmat/zbom#78]
I have found two issues while playing through so far.

1) the bridge right to the left of the warp septen heights which the carpenter is working on is a little glitched. Not all of the water between the two bridge parts are identified as water. AKA, Their are certain(no so difficult to find) ways you can cross the bridge without an difficulty which lets you get to the other continent.

2) This is a miner one, when selecting warp points on the map, when selecting ones that are higher up; Septen Heights, and Kakariko Village, you can get to see part of the other continent to the north.

**Comment by Ezkazelda** [comment]
Also if you cross the bridge all the way, you are unable to get back onto it

**Comment by Ezkazelda** [comment]
Their is also another block glitch I just found, 
![screen shot 2017-01-11 at 6 57 57 pm](https://cloud.githubusercontent.com/assets/24845404/21872753/fe3d34e0-d82f-11e6-98b1-43fb8bb55efd.png)

**Comment by Ezkazelda** [comment]
I am unable to move from that spot

**Comment by Ezkazelda** [comment]
Also the map is still a little messed up
![screen shot 2017-01-11 at 7 11 59 pm](https://cloud.githubusercontent.com/assets/24845404/21873110/f6497e68-d831-11e6-9465-9f5fdb11b79d.png)
![screen shot 2017-01-11 at 7 12 07 pm](https://cloud.githubusercontent.com/assets/24845404/21873115/f77b5c16-d831-11e6-875d-e238df477aad.png)

**Comment by Ezkazelda** [comment]
Also another block glitch I found, if you enter this cave
![screen shot 2017-01-12 at 5 46 05 pm](https://cloud.githubusercontent.com/assets/24845404/21912990/1f805c80-d8ef-11e6-8bf8-66db389a1023.png)
And then go out the exit to the right and jump of the ledge, you get stuck here.
![screen shot 2017-01-12 at 5 45 09 pm](https://cloud.githubusercontent.com/assets/24845404/21912994/2cbdc59a-d8ef-11e6-8592-f3e784400357.png)

**Comment by wrightmat** [comment]
I think I'm done doing minor tweaks to the map, but the other issues are fixed.
