### ISSUE TITLE
Damage against enemies stops working (randomly?)

### ISSUE THREAD

**Issue by Ezkazelda** [wrightmat/zbom#80]
![screen shot 2017-01-12 at 6 11 11 pm](https://cloud.githubusercontent.com/assets/24845404/21913745/02dfa4b4-d8f4-11e6-89b1-afdda02c4a56.png)
This boss fight was very confusing at first. I had no Idea what to do because 

1) the boss and its little heads it gave out didn't to any damage to you. So that is kind of a big issue
2) Attacking it seems kind of glitches

**Comment by wrightmat** [comment]
The boss and the heads can definitely both hurt you. Did you have an error.txt file that was generated? I wondering if there was a bug during your playthrough that didn't show in my testing.

You'll have to be more specific about the attacking, I don't know what you mean...

**Comment by Ezkazelda** [comment]
Im sorry but I don't recall any error message( probably because I didn't look, my bad) however I believe it would probably be find if I could go back and fight the boss again. As I referenced in my post to the wind temple issues, I think their was some problem just with that play through of the game. I am sorry for any problems I have caused you for false reports, you have done an amazing job on this game and so far, It is my favorite made with this engine.

**Comment by wrightmat** [comment]
No need to apologize, I appreciate the reports. I'm just honestly pretty burned out on this game and will probably only be fixing major issues and things that interest me, lol

**Comment by blakeney** [comment]
When I played through this part of the game today, I also noticed that this boss didn't inflict any damage, and it doesn't look like anything showed up in error.txt.

A bit more information, though:  I noticed that it wasn't just this boss that didn't do damage.  I believe that all damage stopped working at some point while I was playing this dungeon (or perhaps exploring the surrounding overworld), as other enemies were also affected.  The problem went away after I saved and restarted the game.

**Comment by wrightmat** [comment]
I believe there's a more general issue than just the ice temple boss mentioned in the original issue. I will keep this one open, but I don't know how to fix it right now since it hasn't come up in my testing. Any insights from other players would be appreciated!

**Comment by MetalES** [comment]
It might be related to hero states, I were frozen by an enemy and now Link is invincible

**Comment by MetalES** [comment]
I were frozen by a bubble in the Ice Temple, since then I am invincible, is it related ?
