### ISSUE TITLE
Cave of Ordeals

### ISSUE THREAD

**Issue by Ezkazelda** [wrightmat/zbom#82]
In the cave of ordeals after going through the first few floors. Right when you teleport to the next the enemies hit you right when you teleport you which glitch you into the wall making you unable to continue. An easy fix without doing much would just be moving the teleports away from the wall

**Comment by wrightmat** [comment]
Already logged and corrected as issue #72. It will be corrected in the next release, or you could download the code from here to get the bleeding edge corrections.

**Comment by Ezkazelda** [comment]
I moved the portals away from myself using the editor, the only thing that happened then was usually getting hit right away when teleporting in(which was annoying, but was fine), however when I reached the electric chuchu, when I got electrocuted i couldn't move link anymore. A fix might be to have a little area in which the enemies don't spawn where you have time to rest.

**Comment by wrightmat** [comment]
I'll probably try to add walls that only block enemies around the transporters. When I get home :)
