### ISSUE TITLE
Bubbles makes Link Invincible & Ice Temple boss problems

### ISSUE THREAD

**Issue by MetalES** [wrightmat/zbom#83]
After several hours of playtesting to finally understand what makes Link invincible some times. Finally found it.

If you go throuk the Ice Temple, there is a corridor where there is two Ice bubbles, touching them will freeze Link, this is the normal and attended behaviour, the problem, if Link got unfreezed, Link become instantaniously invincible, so no one can hurt him anyway. You can cancel this by being freezed by the Ice Temple's miniboss, if you haven't beat him or just save and reload the game.
(This makes the Tower of Wind insanely easier.)

In earlier versions of Book of Mudora, this bug allowed to wrong warp (without any logic) straight to Cave of Ordeals or some dungeon, looks like this is fixed

Map stuffs like holes, water and lava still works.
This might be related to issue #80

https://www.youtube.com/watch?v=cETUucWVut8&feature=youtu.be

Yet, something is strange for the boss, and I can confirm it, killing the heads works, but it looks like their collision are still on the map, placing a bomb and throwing a bomb on where you killed the head makes the bomb explode, as if there were still the collision.

**Comment by wrightmat** [comment]
Excellent find, MetalES, thanks!!! And the video was a huge help!
