### ISSUE TITLE
Unreachable key in Lakebed Lair

### ISSUE THREAD

**Issue by joptimus7** [wrightmat/zbom#88]
Hi Matt,

in Lakebed Lair if you open the looked doors in BF1 level, there is the possibility to get it wrong. I.e. not being able to open all of them, since the last key (for the "southern" door) is just behind that door.
That seems to be a bug since the player cannot know which doors to open first.

Is there a way to edit the save game to provide that key? I don't want to repeat the whole game just because of that bug.

Thanks for the game, I'm enjoying it very much nonetheless!

**Comment by wrightmat** [comment]
As explained in the Solarus forum, this key can be obtained by an NPC after the dungeon is completed. I know the key has already been obtained in this game, so I'm going to go ahead and close the issue.
