### ISSUE TITLE
Sleeping does not restore the stamina bar

### ISSUE THREAD

**Issue by christopho** [wrightmat/zbom#9]
Version 0.42
Contrary to what the NPCs say, sleeping in the bed has no effect.
My stamina bar was empty or almost empty. I tried to sleep in the bed in Link's house, and also in the inn in the northern village, but my stamina bar was not restored.

**Comment by wrightmat** [comment]
The sleeping process did seem to work at all, since the game also did not transition to night time. I noticed this in your play through, but was not able to recreate it. Do you have an error log from this time? Would you be willing to try with the new version and see if you still have the problem?

**Comment by christopho** [comment]
It now works well with the git version! Thanks!
