### ISSUE TITLE
Two Town Flowers (but no Pikit Plant?)

### ISSUE THREAD

**Issue by Maximini1010** [wrightmat/zbom#90]
Searching in the quest editor for the 3 books and the plant I can't find (I'm not done checking each map yet), I found 2 different locations for the Town Flower.

One is in Rauru Town (which is probably the right one, given the name). The other is in the Nabooru Oasis. It's wierd than there is 2 copies of that plant when you can only get one. Would the other be mislabelled?

**Comment by wrightmat** [comment]
Yes, a few of the plants grow in more than one location :)

A hint if you'd like it - the Pikit Plant grows in swampy areas...
