### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by ghost** [wrightmat/zbom#94]
I recently decided to replay my favorite game, this, and while doing so it seemed that a lot of the text was off. For example, M looked like N, and other simular letters. I think that the font is messed up or something, or you should just switch back to the ALTTP font.

**Comment by wrightmat** [comment]
I have to use a monospace font in order for the colored dialogs to work correctly (without a bunch of padding spaces that cause major problems with translations). The one being used is the best I could find that was still mostly legible at the small font sizes.

**Comment by wrightmat** [comment]
Font seems to be working well, and I will almost certainly keep it when the next version is released.
