### ISSUE TITLE
Cant get boomerang in sewers at all 

### ISSUE THREAD

**Issue by fallenslayerx1** [wrightmat/zbom#95]
I cant get the boomerang from the sewers and it does not generate in the error.txt file about it not loading.

**Comment by wrightmat** [comment]
Is the chest not there (in the central pedestal) at all, or is it there and empty? Have you already received a boomerang from somewhere else?

**Comment by fallenslayerx1** [comment]
nope was using the wrong version downloaded 1.2 on accident got 1.3 and issue was fixed however i have found another issue the chest south of the subrosian beach that requires the feather to get crashes the game and i am not replying from my desktop which has the game so i cant give exact error issue from error text however i still cant find the forest fairy or the purple tunic and where is the giant crab boss from the trailer.
