### ISSUE TITLE
Analogic Controler Bug

### ISSUE THREAD

**Issue by Darknior** [wrightmat/zbom#97]
Hi
I think there are some other menu bugs in your game.
I correct the **PAUSE** menu and the **START (SAVE)** menu, but i also see a WARP menu ?
I'm at the beginning of the game. I d'ont have them all and can't try them to fix bugs.
Is it possible that you send me here a **savegame** where all the menu are available ?
I will try them all fix and pull request. Thanks.

**Comment by wrightmat** [comment]
Should just be the warp menu left that takes input. I didn't see the fix to the savegame menu though - did it get missed in the pull request?
