### ISSUE TITLE
Tower of winds miniboss is invincible

### ISSUE THREAD

**Issue by digitalshadowhawk** [wrightmat/zbom#98]
I've tried fighting this thing for days now, but nothing I do seems to damage it. poking into the lua file for this guy, it seems there's nothing that makes him vulnerable again

**Comment by digitalshadowhawk** [comment]
it looks like he's supposed to start moving around after finishing spawning keese, but he just sits there. in the end, I hacked my save file for variable b1166 to bypass the grim creeper

**Comment by wrightmat** [comment]
@digitalshadowhawk  Did you try throwing bombs at him? I double checked the script, and he is vulnerable to explosions at all times, like he should be.

**Comment by Wuzzy2** [comment]
I was able to beat this miniboss in 1.4.

By using lots of bombs and throwing them over the ledge. I was stumped by this miniboss at first, too. I didn't really notice the bombs actually dealt damage. Strange. Why did I not notice it the first time? Maybe you just don't notice it with all the bats flying around the screen. On my second try I finally noticed. 

And yes, I can confirm that at one point, the bats just stop spawning.
I can also confirm this miniboss never moves.

**Comment by wrightmat** [comment]
This boss is not designed to move around - he stays on his ledge and you thrown bombs at him. Any ideas on how to make this more apparent, or to make this boss better?

**Comment by Wuzzy2** [comment]
I have no suggestions because I don't think it's a problem in the first place.

**Comment by wrightmat** [comment]
Closing since the boss is working as designed.
